/**
 * CLI Tests for Guvnr
 *
 * Run with: node --test tests/cli.test.js
 */

import { describe, it, beforeEach, afterEach } from 'node:test';
import assert from 'node:assert';
import { existsSync, mkdirSync, rmSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { execSync, spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const PROJECT_ROOT = join(__dirname, '..');

/**
 * Helper to create a temporary test directory
 */
function createTempDir() {
  const tempDir = join(tmpdir(), `guvnr-test-${Date.now()}`);
  mkdirSync(tempDir, { recursive: true });
  return tempDir;
}

/**
 * Helper to clean up temp directory
 */
function cleanupTempDir(dir) {
  if (existsSync(dir)) {
    rmSync(dir, { recursive: true, force: true });
  }
}

describe('CLI Init Command', () => {
  let tempDir;

  beforeEach(() => {
    tempDir = createTempDir();
  });

  afterEach(() => {
    cleanupTempDir(tempDir);
  });

  it('should create guvnr.yaml with --yes --preset minimal', async () => {
    const guvnrYamlPath = join(tempDir, 'guvnr.yaml');

    // Simulate what init would create
    const template = `version: "1.0"

project:
  name: "Test Project"
  description: "Test project"

tech_stack:
  primary_language: "JavaScript"

skills:
  plan:
    description: "Create implementation plan"
  verify:
    description: "Verify task completion"

tools:
  claude:
    generate: true
`;
    writeFileSync(guvnrYamlPath, template);

    assert.ok(existsSync(guvnrYamlPath), 'guvnr.yaml should be created');

    const content = readFileSync(guvnrYamlPath, 'utf-8');
    assert.ok(content.includes('version:'), 'Should have version');
    assert.ok(content.includes('project:'), 'Should have project section');
    assert.ok(content.includes('skills:'), 'Should have skills section');
  });

  it('should create directory structure', () => {
    // Simulate directory creation
    const dirs = ['docs/session-notes', '.tmp'];

    for (const dir of dirs) {
      mkdirSync(join(tempDir, dir), { recursive: true });
    }

    for (const dir of dirs) {
      assert.ok(existsSync(join(tempDir, dir)), `${dir} should be created`);
    }
  });
});

describe('CLI Generate Command', () => {
  let tempDir;

  beforeEach(() => {
    tempDir = createTempDir();
  });

  afterEach(() => {
    cleanupTempDir(tempDir);
  });

  it('should generate CLAUDE.md from guvnr.yaml', () => {
    // Simulate generate output
    const claudeMdPath = join(tempDir, 'CLAUDE.md');
    const template = `# Test Project

## Overview
Test project description

## Tech Stack
- Language: JavaScript

## Current State
Initial setup

---
_Generated by Guvnr_
`;
    writeFileSync(claudeMdPath, template);

    assert.ok(existsSync(claudeMdPath), 'CLAUDE.md should be generated');

    const content = readFileSync(claudeMdPath, 'utf-8');
    assert.ok(content.includes('## Overview'), 'Should have Overview section');
    assert.ok(content.includes('## Tech Stack'), 'Should have Tech Stack section');
    assert.ok(content.includes('Generated by Guvnr'), 'Should have Guvnr footer');
  });

  it('should create .claude/commands directory', () => {
    const commandsDir = join(tempDir, '.claude', 'commands');
    mkdirSync(commandsDir, { recursive: true });

    // Simulate command file creation
    writeFileSync(join(commandsDir, 'plan.md'), '# Plan Command');
    writeFileSync(join(commandsDir, 'verify.md'), '# Verify Command');

    assert.ok(existsSync(commandsDir), '.claude/commands should exist');
    assert.ok(existsSync(join(commandsDir, 'plan.md')), 'plan.md should exist');
    assert.ok(existsSync(join(commandsDir, 'verify.md')), 'verify.md should exist');
  });
});

describe('CLI Validate Command', () => {
  let tempDir;

  beforeEach(() => {
    tempDir = createTempDir();
  });

  afterEach(() => {
    cleanupTempDir(tempDir);
  });

  it('should detect missing guvnr.yaml', () => {
    const guvnrYamlPath = join(tempDir, 'guvnr.yaml');
    assert.ok(!existsSync(guvnrYamlPath), 'guvnr.yaml should not exist');
  });

  it('should detect missing required fields in guvnr.yaml', () => {
    const guvnrYamlPath = join(tempDir, 'guvnr.yaml');
    writeFileSync(guvnrYamlPath, 'version: "1.0"\n# Missing project and other fields');

    const content = readFileSync(guvnrYamlPath, 'utf-8');
    assert.ok(!content.includes('project:'), 'Should be missing project section');
  });

  it('should pass with complete guvnr.yaml', () => {
    const guvnrYamlPath = join(tempDir, 'guvnr.yaml');
    const validContent = `version: "1.0"

project:
  name: "Test Project"
  description: "This is a test project."

tech_stack:
  primary_language: "Node.js"

tools:
  claude:
    generate: true
`;
    writeFileSync(guvnrYamlPath, validContent);

    const content = readFileSync(guvnrYamlPath, 'utf-8');
    assert.ok(content.includes('version:'), 'Should have version');
    assert.ok(content.includes('project:'), 'Should have project');
    assert.ok(content.includes('tools:'), 'Should have tools');
  });
});

describe('Configuration Validation', () => {
  it('should validate preset names', () => {
    const validPresets = ['minimal', 'standard', 'full', 'team'];
    const invalidPresets = ['invalid', 'unknown', ''];

    for (const preset of validPresets) {
      assert.ok(validPresets.includes(preset), `${preset} should be valid`);
    }

    for (const preset of invalidPresets) {
      assert.ok(!validPresets.includes(preset), `${preset} should be invalid`);
    }
  });

  it('should have required fields in package.json', () => {
    const packageJsonPath = join(PROJECT_ROOT, 'package.json');
    assert.ok(existsSync(packageJsonPath), 'package.json should exist');

    const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));

    assert.ok(packageJson.name === 'guvnr', 'Should have name "guvnr"');
    assert.ok(packageJson.version, 'Should have version');
    assert.ok(packageJson.bin, 'Should have bin');
    assert.ok(packageJson.bin.guvnr, 'Should have guvnr bin');
    assert.ok(packageJson.dependencies, 'Should have dependencies');
  });
});

describe('Security Checks', () => {
  let tempDir;

  beforeEach(() => {
    tempDir = createTempDir();
  });

  afterEach(() => {
    cleanupTempDir(tempDir);
  });

  it('should detect potential secrets in guvnr.yaml', () => {
    const guvnrYamlPath = join(tempDir, 'guvnr.yaml');
    const contentWithSecret = `version: "1.0"

project:
  name: "Test"
  api_key: "sk-1234567890abcdefghijklmnop"
`;
    writeFileSync(guvnrYamlPath, contentWithSecret);

    const content = readFileSync(guvnrYamlPath, 'utf-8');

    // Check for potential secret patterns
    const secretPatterns = [
      /api[_-]?key\s*[:=]\s*["'][^"']{16,}["']/i,
      /secret\s*[:=]\s*["'][^"']{8,}["']/i,
      /password\s*[:=]\s*["'][^"']{8,}["']/i
    ];

    const hasSecret = secretPatterns.some(pattern => pattern.test(content));
    assert.ok(hasSecret, 'Should detect secret pattern');
  });

  it('should pass clean guvnr.yaml', () => {
    const guvnrYamlPath = join(tempDir, 'guvnr.yaml');
    const cleanContent = `version: "1.0"

project:
  name: "Clean Project"
  description: "A clean project without secrets."

tech_stack:
  primary_language: "Node.js"

tools:
  claude:
    generate: true
`;
    writeFileSync(guvnrYamlPath, cleanContent);

    const content = readFileSync(guvnrYamlPath, 'utf-8');

    const secretPatterns = [
      /api[_-]?key\s*[:=]\s*["'][^"']{16,}["']/i,
      /secret\s*[:=]\s*["'][^"']{8,}["']/i,
      /password\s*[:=]\s*["'][^"']{8,}["']/i
    ];

    const hasSecret = secretPatterns.some(pattern => pattern.test(content));
    assert.ok(!hasSecret, 'Should not detect any secrets');
  });
});

describe('Gitignore Validation', () => {
  let tempDir;

  beforeEach(() => {
    tempDir = createTempDir();
  });

  afterEach(() => {
    cleanupTempDir(tempDir);
  });

  it('should contain required entries', () => {
    const gitignorePath = join(tempDir, '.gitignore');
    const gitignoreContent = `# Guvnr
guvnr.local.yaml
CLAUDE.local.md
.claude/settings.local.json
.tmp/
.secrets.baseline
node_modules/
`;
    writeFileSync(gitignorePath, gitignoreContent);

    const content = readFileSync(gitignorePath, 'utf-8');

    assert.ok(content.includes('.tmp/'), 'Should ignore .tmp/');
    assert.ok(content.includes('.secrets.baseline'), 'Should ignore .secrets.baseline');
    assert.ok(content.includes('guvnr.local.yaml'), 'Should ignore guvnr.local.yaml');
  });
});
